# Generated by Django 4.2.23 on 2025-09-02 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('duration_minutes', models.IntegerField(choices=[(15, '15分'), (30, '30分'), (60, '1時間'), (120, '2時間'), (240, '4時間'), (480, '8時間'), (720, '12時間')], default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tracker.locationsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'is_active'], name='tracker_web_session_decdf8_idx'), models.Index(fields=['participant_id', 'is_active'], name='tracker_web_partici_025cab_idx')],
                'unique_together': {('session', 'participant_id', 'channel_name')},
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'セッション作成'), ('joined', '参加'), ('left', '退出'), ('expired', '期限切れ'), ('location_updated', '位置更新'), ('websocket_connected', 'WebSocket接続'), ('websocket_disconnected', 'WebSocket切断'), ('error', 'エラー')], max_length=50)),
                ('participant_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('connection_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.locationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'action'], name='tracker_ses_session_79f120_idx'), models.Index(fields=['participant_id', 'timestamp'], name='tracker_ses_partici_e15460_idx'), models.Index(fields=['action', 'timestamp'], name='tracker_ses_action_9bea46_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50)),
                ('participant_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_background', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('connection_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('movement_speed', models.FloatField(default=0, help_text='移動速度 (km/h)')),
                ('last_position_lat', models.FloatField(blank=True, null=True)),
                ('last_position_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', '共有待機中'), ('sharing', '共有中'), ('stopped', '共有停止中')], default='waiting', max_length=20)),
                ('has_shared_before', models.BooleanField(default=False, help_text='一度でも位置情報を共有した履歴')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='最後に確認した時刻', null=True)),
                ('stay_start_time', models.DateTimeField(blank=True, help_text='現在位置での滞在開始時刻', null=True)),
                ('last_move_time', models.DateTimeField(blank=True, help_text='最後に移動した時刻', null=True)),
                ('total_stay_minutes', models.IntegerField(default=0, help_text='累計滞在時間（分）')),
                ('persistent_participant_id', models.CharField(blank=True, db_index=True, help_text='IPアドレスが変わっても同一参加者を識別するための永続ID', max_length=100, null=True)),
                ('session_fingerprint', models.CharField(blank=True, db_index=True, help_text='ブラウザ固有の識別子（Canvas fingerprint等）', max_length=100, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracker.locationsession')),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['session', 'is_active'], name='tracker_loc_session_9e28d8_idx'), models.Index(fields=['participant_id', 'last_updated'], name='tracker_loc_partici_99883a_idx'), models.Index(fields=['session', 'is_active', 'last_updated'], name='tracker_loc_session_fc7906_idx'), models.Index(fields=['session', 'persistent_participant_id', 'is_active'], name='loc_persistent_idx'), models.Index(fields=['session', 'session_fingerprint', 'is_active'], name='loc_fingerprint_idx')],
                'unique_together': {('session', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatUnreadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100)),
                ('group_unread', models.IntegerField(default=0)),
                ('individual_unread', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.locationsession')),
            ],
            options={
                'unique_together': {('session', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('group', 'グループ'), ('individual', '個別')], max_length=20)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tracker.locationsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'chat_type', 'timestamp'], name='tracker_cha_session_02fe89_idx'), models.Index(fields=['sender_id', 'target_id'], name='tracker_cha_sender__12f3ea_idx'), models.Index(fields=['session', 'is_read'], name='tracker_cha_session_a2c70b_idx')],
            },
        ),
    ]
